# Site Settings 
title: "Sneaker Resale Analysis"
description: "An analysis of sneakers on the resale market" 
url: "https://jnapeloni.github.io/sneaker-resale-analysis/"
author: Jack Napeloni 

# Theme Settings 
theme: minima

header_pages: 
  - data.md  
  - methodology.md  
  - results.md  
  - conclusion.md  
  
# Plugins 
plugins: 
  - jekyll-feed  
  - jekyll-seo-tag  
  - jekyll-sitemap

# Markdown Settings 
markdown: kramdown
highlighter: rogue 
